name: CI Build

on: [pull_request]

jobs:
  ROOT5:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/star-bnl/star-sw-root5-base@sha256:4bed8a8b729fa9e6c8e92b2bdecd6b73869e67a07bfbde969936f921123d4c3e
          push: false
          tags: ghcr.io/star-bnl/star-sw-root5-build
          file: docker/Dockerfile.root5
          outputs: type=docker,dest=/tmp/star-sw-root5-build.tar

      - name: Save built image for test jobs
        uses: actions/upload-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp/star-sw-root5-build.tar

  ROOT6:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/star-bnl/star-sw-root6-base@sha256:107736be0e111ef9eaac37281f9bcad95769ab3ce75a4c9624d8cea98b1eb966
          push: false
          tags: ghcr.io/star-bnl/star-sw-root6-build
          file: docker/Dockerfile.root6

  ROOT5_test_job87:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "pp2017,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")'

  ROOT5_test_job88:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "pp2017,StiCA,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")'

  ROOT5_test_job89:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "pp2017,Sti,hitreuseon,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")'

  ROOT5_test_job101:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "P2018a,Sti,btof,mtd,PicoVtxDefault,BEmcChkStat,QAalltrigs,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_19136012_raw_1000016.daq")'

  ROOT5_test_job102:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "P2018a,StiCA,btof,mtd,PicoVtxDefault,BEmcChkStat,QAalltrigs,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_19136012_raw_1000016.daq")'

  ROOT5_test_job103:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "P2018a,Sti,hitreuseon,btof,mtd,PicoVtxDefault,BEmcChkStat,QAalltrigs,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_19136012_raw_1000016.daq")'
